### PR TITLE
Add support for using a custom Tenant Id.

### PR DESCRIPTION
**Pull request by mikehc**
If you setup discourse API keys in Azure/Office365 as a standalone app (not multitenant) you need to define a Tenant Id when trying to authenticate. This PR adds support to adding a custom Tenant Id if necessary, if not defined the "common" tenant is used.

### CODE REVIEW

**Comment by Genzer** [comment]
Hi @jordanvidrine 

Is it possible to merge this PR? Since Microsoft requires only Verified Publishers to be able to use the "common" tenant, our internal company instance cannot use Microsoft Office365 to login.

Much appreciated!
Genzer

**Comment by mhurtado-asp** [comment]
I ended up using my own repository to have the functionality. I never got a response from the Discourse team/maintainers.

**Comment by Genzer** [comment]
Hi Mike Hurtado,

Thanks a lot for your work! I also did the same actually.

Regards,
Genzer

**Comment by Genzer** [comment]
For future visitors like me, you may choose the approach I took. I changed to use https://github.com/discourse/discourse-openid-connect instead because it allowed to fine-grained configure the options (the /.well-known/openid-configuration).

One important note: You may want to use the v2.0 version, `https://login.microsoftonline.com/{YOUR_TENANT_UUID}/v2.0/.well-known/openid-configuration`. See https://meta.discourse.org/t/openid-connect-issue-with-azure-ad/105706/24?u=genzerhawker.

**Pull request closed without merging**
